//
// i tried to copy google drive's routing, play around with their site to find out how it works.
//

// @TODO: renaming folders
// @TODO: renaming files
import { Router } from "express";
import { validateAuth } from "../validators/auth.js";
import { prisma } from "../lib/prisma.js";
import multer from "multer";
import path from "path";
import { validateFolderCreationForm } from "../validators/drive.js";
import { matchedData, validationResult } from "express-validator";
import { unlink } from "fs";

const storage = multer.diskStorage({
  destination: "uploads/",
  filename: (_req, _file, cb) => {
    const uuid = crypto.randomUUID();
    cb(null, uuid);
  },
});
const upload = multer({ storage: storage });

const router = Router();

router.get("/{folders}", validateAuth, (req, res) =>
  res.redirect(req.baseUrl + "/folders/home"),
);

router.get("/folders/home", validateAuth, async (req, res) => {
  try {
    const userInDB = await prisma.user.findUnique({
      where: { id: req.user.id },
      include: {
        rootDir: {
          include: {
            files: true,
            subDirs: true,
          },
        },
      },
    });

    const subdrive = userInDB.rootDir;
    if (!subdrive) {
      throw Error(
        `couldn't find the root drive somehow, user id is ${req.user.id}`,
      );
    }

    res.render("drive", { subdrive, isRoot: true });
  } catch (err) {
    console.error(err);
    return res
      .status(500)
      .send("An error occured, we couldn't fetch your drive...");
  }
});

router.get("/folders/:id", validateAuth, async (req, res) => {
  try {
    const id = Number.parseInt(req.params.id);
    const subdrive = await prisma.directory.findUnique({
      where: {
        id: id,
      },
      include: {
        files: true,
        subDirs: true,
      },
    });

    if (subdrive.ownerId !== req.user.id) {
      return res.status(401).send("Unauthorized.");
    }

    if (!subdrive)
      throw Error(`couldn't find the subdrive somehow, id is ${req.params.id}`);

    res.render("drive", { subdrive, isRoot: subdrive.parentDirId === null });
  } catch (err) {
    console.error(err);
    return res
      .status(500)
      .send("An error occured, we couldn't fetch your drive...");
  }
});

router.get("/files/:uuid", validateAuth, async (req, res) => {
  try {
    const fileMetadata = await prisma.file.findUnique({
      where: {
        uuid: req.params.uuid,
      },
    });

    if (fileMetadata.ownerId !== req.user.id) {
      return res.status(401).send("Unauthorized.");
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileMetadata.name}"`,
    );

    const rootPath = path.join(import.meta.dirname, "..", "uploads/");
    res.sendFile(req.params.uuid, { root: rootPath }, (err) => {
      if (err) {
        console.error("Error sending file:", err);
        res.status(500).send("File not found!");
      }
    });
  } catch (err) {
    console.error(err);
    return res
      .status(500)
      .send("An error occured, we couldn't upload that file...");
  }
});

router.post(
  "/upload-file/:parent_id",
  validateAuth,
  upload.single("file"),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).send("Tried to upload nothing.");
      }

      const parentFolderID = Number.parseInt(req.params.parent_id);
      if (isNaN(parentFolderID)) {
        return res.status(400).send("Invalid directory id.");
      }

      const parentFolder = await prisma.directory.findUnique({
        where: { id: parentFolderID },
        include: {
          files: {
            where: {
              name: req.file.originalname, // include files that have the same name, should only return zero or one file!
            },
          },
        },
      });

      if (parentFolder.ownerId !== req.user.id) {
        return res.status(401).send("Unauthorized.");
      }

      const doesFileAlreadyExist = parentFolder.files.length > 0;
      if (doesFileAlreadyExist) {
        return res
          .status(400)
          .send("File already exists. We haven't implemented overriding...");
      }

      await prisma.file.create({
        data: {
          uuid: req.file.filename, // the filename is generated by multer as a uuid beforehand.
          name: req.file.originalname,
          parentDirId: parentFolderID,
          size: req.file.size,
          ownerId: req.user.id,
        },
      });

      res.redirect(req.baseUrl + "/folders/" + parentFolderID);
    } catch (err) {
      console.error(err);
      return res
        .status(500)
        .send("An error occured, we couldn't upload that file...");
    }
  },
);

router.post(
  "/create-folder/:parent_id",
  validateAuth,
  validateFolderCreationForm,
  async (req, res) => {
    try {
      const result = validationResult(req);
      if (!result.isEmpty()) {
        // @TODO: put errors next to the form
        return res.status(400).send(result.array());
      }

      const { folder_name } = matchedData(req);
      const parentFolderID = Number.parseInt(req.params.parent_id);
      if (isNaN(parentFolderID)) {
        return res.status(400).send("Invalid directory id.");
      }

      const parentFolder = await prisma.directory.findUnique({
        where: {
          id: parentFolderID,
        },
        include: {
          subDirs: {
            where: {
              // include subdirs that have the same name, should only return zero or one subdir!
              parentDirId: parentFolderID,
              name: folder_name,
            },
          },
        },
      });

      if (parentFolder.ownerId !== req.user.id) {
        return res.status(401).send("Unauthorized.");
      }

      const doesDirAlreadyExist = parentFolder.subDirs.length > 0;
      if (doesDirAlreadyExist) {
        return res
          .status(400)
          .send("There exists a directory with the same name.");
      }

      await prisma.directory.create({
        data: {
          name: folder_name,
          parentDirId: parentFolderID,
          ownerId: req.user.id,
        },
      });

      res.redirect(req.baseUrl + "/folders/" + parentFolderID);
    } catch (err) {
      console.error(err);
      return res
        .status(500)
        .send("An error occured, we couldn't create that directory...");
    }
  },
);

router.post("/delete-file/:uuid", validateAuth, async (req, res) => {
  try {
    const fileUUID = req.params.uuid;
    const fileToDelete = await prisma.file.findUnique({
      where: {
        uuid: fileUUID,
      },
    });

    if (fileToDelete.ownerId !== req.user.id) {
      return res.status(401).send("Unauthorized.");
    }

    // delete row first to ensure its existence, it will just throw if not existing.
    await prisma.file.delete({
      where: {
        uuid: fileUUID,
      },
    });

    // then delete from storage
    const filePath = path.join("uploads/", fileToDelete.uuid);
    console.log(`Deleteing ${filePath}`); // @TEMP ?
    unlink(filePath, (err) => {
      if (err) {
        console.error(
          `Error while trying to delete ${fileToDelete.uuid}: ${err}`,
        );
      }
    });

    res.redirect(req.baseUrl + "/folders/" + fileToDelete.parentDirId);
  } catch (err) {
    console.error(err);
    return res
      .status(500)
      .send("An error occured, we couldn't delete that file...");
  }
});

router.post("/delete-folder/:id", validateAuth, async (req, res) => {
  try {
    const folderId = Number.parseInt(req.params.id);
    if (isNaN(folderId)) {
      return res.status(400).send("Invalid directory id.");
    }

    const folderToDelete = await prisma.directory.findUnique({
      where: {
        id: folderId,
      },
    });

    if (folderToDelete.ownerId !== req.user.id) {
      return res.status(401).send("Unauthorized.");
    }

    // first, get all files nested inside this dir,
    // we get them using a recursive CTE (needs a raw query).
    // this is to get all of their uuids to remove them from the actual storage.
    const files = await prisma.$queryRaw`
			WITH RECURSIVE nested_dirs AS (
				SELECT id FROM "Directory"
				WHERE id = ${folderId}
				UNION ALL
				SELECT d.id
				FROM "Directory" d
				JOIN nested_dirs n
				ON d."parentDirId" = n.id
			)
			SELECT * FROM "File"
			WHERE "parentDirId" IN (SELECT id FROM nested_dirs)
		`;

    // then, delete them from storage
    files.forEach((file) => {
      const filePath = path.join("uploads/", file.uuid);
      console.log(`Deleteing ${filePath}`); // @TEMP ?
      unlink(filePath, (err) => {
        // we just print the error and continue.
        if (err)
          console.error(`Error while trying to delete ${file.uuid}: ${err}`);
      });
    });

    // then delete the dir, the dir and file rows in the db will be deleted by cascade.
    await prisma.directory.delete({
      where: {
        id: folderId,
      },
    });

    res.redirect(req.baseUrl);
  } catch (err) {
    console.error(err);
    return res
      .status(500)
      .send("An error occured, we couldn't delete that directory...");
  }
});

export default router;
